"""add_avatar_and_friendship

Revision ID: 468a9a41b845
Revises: cacce83c00eb
Create Date: 2026-07-06 17:24:47.724192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '468a9a41b845'
down_revision: Union[str, Sequence[str], None] = 'cacce83c00eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'friend_id')
    )
    op.add_column('users', sa.Column('avatar_path', sa.String(), nullable=True))
    op.execute("UPDATE users SET level = 0 WHERE level IS NULL")
    op.alter_column('users', 'level',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('users', 'avatar_path')
    op.drop_table('friendships')
    # ### end Alembic commands ###
