"""add_intra_id

Revision ID: 5a583dcbbdbd
Revises: 468a9a41b845
Create Date: 2026-07-06 16:30:22.046565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a583dcbbdbd'
down_revision: Union[str, Sequence[str], None] = '468a9a41b845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('intra_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_intra_id'), 'users', ['intra_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_intra_id'), table_name='users')
    op.drop_column('users', 'intra_id')
    # ### end Alembic commands ###
