"""add_ai_depth

Revision ID: 90b129da2118
Revises: 5a583dcbbdbd
Create Date: 2026-07-06 21:15:55.384466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90b129da2118'
down_revision: Union[str, Sequence[str], None] = '5a583dcbbdbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('ai_depth', sa.Integer(), nullable=False, server_default='3'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'ai_depth')
    # ### end Alembic commands ###
