"""add_game_and_move_models

Revision ID: cacce83c00eb
Revises: 44b3c5516d08
Create Date: 2026-06-17 18:41:08.861485

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cacce83c00eb"
down_revision: Union[str, Sequence[str], None] = "44b3c5516d08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_white_id", sa.Integer(), nullable=True),
        sa.Column("player_black_id", sa.Integer(), nullable=True),
        sa.Column("current_turn", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("winner_id", sa.Integer(), nullable=True),
        sa.Column("grid_size", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_black_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_white_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["winner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_games_id"), "games", ["id"], unique=False)
    op.create_table(
        "moves",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("move_number", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("from_cell", sa.String(), nullable=False),
        sa.Column("to_cell", sa.String(), nullable=False),
        sa.Column("played_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("game_id", "move_number", name="uq_game_move_number"),
    )
    op.create_index(op.f("ix_moves_id"), "moves", ["id"], unique=False)
    op.add_column("users", sa.Column("level", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "level")
    op.drop_index(op.f("ix_moves_id"), table_name="moves")
    op.drop_table("moves")
    op.drop_index(op.f("ix_games_id"), table_name="games")
    op.drop_table("games")
    # ### end Alembic commands ###
