"""add mmr column

Revision ID: d3e21c5234ea
Revises: 90b129da2118
Create Date: 2026-07-07 12:35:34.301518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e21c5234ea'
down_revision: Union[str, Sequence[str], None] = '90b129da2118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mmr', sa.Integer(), nullable=False))
    op.drop_column('users', 'avatar_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mmr')
    # ### end Alembic commands ###
